### ISSUE TITLE
Streaming inputs

### ISSUE THREAD

**Issue by simra** [UKPLab/iwcs2017-answer-selection#1]
Hi, I'm curious to know whether you or colleagues have implemented a streaming implementation for your QAData class.  My inputs are too large to fit in RAM and I'm looking to find a way to change get_fold_data to return an iterator.

**Comment by arueckle** [comment]
Unfortunately not. 

I believe it would require additional changes when building the vocab. Currently the software builds the vocab dynamically after we read the full dataset. In your case with streaming data, you would need to build the vocab with another method (e.g. by reading an external vocab file, using everything in the embeddings file, etc.).
Also, the training procedure would have to change. Right now we are doing negative sampling from the whole training set at runtime. With streaming data you probably would need to build these samples in the data generator (we create them in the training module).

**Comment by simra** [comment]
Thanks, I'll look into making these changes.
